export const BOOKING_RECOVERY_CONFIG = {
  LONG_STAY_NIGHTS: 11,
  LARGE_SHIFT_DAYS: 7,
  MAX_PRICE_DELTA_PERCENT: 20,
  GEO_RADIUS_KM: 10,
  MAX_SPLIT_PROPERTIES: 2,
  EXACT_OPTIONS_LIMIT: 5,
  ALT_OPTIONS_LIMIT: 3,
  SEARCH_WINDOW_DAYS: 30,
} as const;

export type BookingRecoveryConfig = typeof BOOKING_RECOVERY_CONFIG;
