import type { CoreMirrorJob } from "./types";

export const coreMirrorJobs: CoreMirrorJob[] = [
  {
    id: "ct-j-001",
    slug: "hospitality-manager-halkidiki",
    title: "Hospitality Manager",
    roleType: "full-time",
    category: "hospitality",
    location: "Pefkohori",
    region: "Halkidiki",
    country: "Greece",
    description: "We are looking for an experienced Hospitality Manager to oversee daily operations of a portfolio of 15+ vacation rental properties in Halkidiki. You will manage guest communications, coordinate cleaning and maintenance teams, and ensure high satisfaction scores.",
    requirements: ["3+ years hospitality management", "Fluent English and Greek", "Experience with property management software", "Valid driving license", "Availability during peak season (May-Oct)"],
    benefits: ["Competitive salary", "Performance bonuses", "Accommodation during season", "Company vehicle"],
    salaryRange: "1,800 - 2,500 EUR/month",
    companyName: "ClickyTour Operations",
    contactEmail: "jobs@clickytour.com",
    status: "open",
  },
  {
    id: "ct-j-002",
    slug: "maintenance-technician-corfu",
    title: "Maintenance Technician",
    roleType: "seasonal",
    category: "maintenance",
    location: "Corfu Town",
    region: "Corfu",
    country: "Greece",
    description: "Seasonal maintenance technician needed for a group of vacation properties in Corfu. Responsible for pool maintenance, minor plumbing and electrical repairs, appliance troubleshooting, and pre-arrival property checks.",
    requirements: ["Basic plumbing and electrical skills", "Pool maintenance certification preferred", "Own tools", "Flexible schedule including weekends"],
    benefits: ["Seasonal contract (May-October)", "Weekly pay", "Mileage reimbursement"],
    salaryRange: "1,200 - 1,600 EUR/month",
    companyName: "Corfu Property Services",
    contactEmail: "hiring@corfu-services.gr",
    status: "open",
  },
  {
    id: "ct-j-003",
    slug: "portfolio-manager-athens",
    title: "Property Portfolio Manager",
    roleType: "full-time",
    category: "management",
    location: "Athens",
    region: "Attica",
    country: "Greece",
    description: "Join our growing team in Athens to manage a diverse portfolio of real estate and vacation rental assets. You will work with property owners, coordinate with local service providers, and optimize revenue through dynamic pricing and channel management.",
    requirements: ["5+ years in property/asset management", "Strong analytical skills", "Experience with OTAs (Airbnb, Booking.com)", "Fluent English, Greek; German or Russian a plus", "Bachelor degree in Business or related field"],
    benefits: ["Competitive salary + performance bonus", "Remote work 2 days/week", "Health insurance", "Career growth in a fast-scaling company"],
    salaryRange: "2,500 - 3,500 EUR/month",
    companyName: "ClickyTour HQ",
    contactEmail: "careers@clickytour.com",
    status: "open",
  },
];
