import type { CoreMirrorProperty } from "./types";

export const coreMirrorProperties: CoreMirrorProperty[] = [
  {
    id: "ct-p-001",
    slug: "villa-azure-halkidiki",
    title: "Villa Azure Halkidiki",
    headline: "Luxury Sea-View Villa with Private Pool",
    shortDescription: "Premium 4-bedroom villa overlooking the Aegean Sea, steps from Pefkohori beach.",
    detailDescription: "Villa Azure Halkidiki blends modern luxury with Greek coastal charm. Spacious open-plan living areas flow into a sun-drenched terrace with infinity pool and panoramic sea views. Ideal for families and groups seeking a high-comfort vacation base with easy access to beaches, restaurants, and local services.",
    type: "vacation",
    dealTypes: ["short_term_rent", "monthly_rent"],
    status: "active",
    location: { area: "Pefkohori", region: "Halkidiki", country: "Greece", beachDistanceM: 450, lat: 39.989, lng: 23.616 },
    metrics: { guests: 8, bedrooms: 4, bathrooms: 3, areaSqm: 220 },
    gallery: [
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?q=80&w=1600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=1600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=1600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?q=80&w=1600&auto=format&fit=crop",
    ],
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    pricing: {
      currency: "EUR",
      basicFromPrice: 180,
      seasonalFromPrice: 280,
      seasonName: "High Season",
      minStayNights: 3,
      seasonalRates: [
        { label: "Low Season", from: "2026-04-01", to: "2026-05-31", nightly: 180 },
        { label: "Mid Season", from: "2026-06-01", to: "2026-06-30", nightly: 230 },
        { label: "High Season", from: "2026-07-01", to: "2026-08-31", nightly: 280 },
        { label: "Shoulder", from: "2026-09-01", to: "2026-10-15", nightly: 200 },
      ],
      unavailableDates: ["2026-07-15", "2026-07-16", "2026-07-17", "2026-07-18", "2026-07-19", "2026-07-20", "2026-07-21"],
    },
    amenities: ["Private Pool", "Wi-Fi", "Air Conditioning", "BBQ", "Parking", "Sea View", "Washing Machine", "Dishwasher", "Smart TV", "Outdoor Dining"],
    highlights: ["450m from beach", "Infinity pool with sea views", "Fully equipped kitchen", "Child-friendly garden"],
    badges: ["Superhost", "Instant Book"],
    policies: { smokingAllowed: false, petsAllowed: true, cancellationSummary: "Free cancellation up to 14 days before check-in.", tourismLicense: "MHTE 09.45.678" },
    nearby: [
      { label: "Beach", value: "450 m" },
      { label: "Airport (SKG)", value: "95 km" },
      { label: "Supermarket", value: "800 m" },
      { label: "Restaurant", value: "600 m" },
      { label: "Pharmacy", value: "1.2 km" },
    ],
    faqs: [
      { q: "Is the pool private?", a: "Yes, the villa has a fully private infinity pool." },
      { q: "Is airport transfer available?", a: "Yes, we can arrange transfers from Thessaloniki Airport (SKG)." },
      { q: "Are pets allowed?", a: "Yes, well-behaved pets are welcome with prior notice." },
    ],
    related: [
      { title: "Seaside Apartment Corfu", href: "/property/vacation/seaside-apartment-corfu", from: 120, image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=800&auto=format&fit=crop" },
    ],
    nearbyServices: [
      { name: "Airport Transfer Halkidiki", detail: "Direct SKG transfer", href: "/service/airport-transfer-halkidiki" },
      { name: "Villa Cleaning Pro", detail: "Professional cleaning", href: "/service/villa-cleaning-pro" },
    ],
    blogPosts: [
      { title: "Best Coastal Towns in Halkidiki", href: "/blog/best-coastal-towns-halkidiki", date: "2026-02-10", excerpt: "Guide to choosing the right coastal base.", image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=800&auto=format&fit=crop" },
    ],
  },
  {
    id: "ct-p-002",
    slug: "crete-stone-house",
    title: "Crete Stone House",
    headline: "Traditional Stone Property in Chania with Investment Potential",
    shortDescription: "Renovated 3-bedroom stone house in Chania Old Town, ideal for sale or rental investment.",
    detailDescription: "A beautifully restored traditional Cretan stone house in the heart of Chania Old Town. Original architectural features blend with modern amenities. Courtyard garden, rooftop terrace with harbor views, and walking distance to the Venetian port. Excellent rental yield history.",
    type: "real-estate",
    dealTypes: ["sale", "monthly_rent", "short_term_rent"],
    status: "active",
    location: { area: "Old Town", region: "Chania, Crete", country: "Greece", lat: 35.518, lng: 24.018 },
    metrics: { guests: 6, bedrooms: 3, bathrooms: 2, areaSqm: 160 },
    gallery: [
      "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?q=80&w=1600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?q=80&w=1600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1598928506311-c55ez63a5eR7?q=80&w=1600&auto=format&fit=crop",
    ],
    pricing: {
      currency: "EUR",
      basicFromPrice: 140,
      minStayNights: 5,
      seasonalRates: [
        { label: "Low Season", from: "2026-11-01", to: "2026-03-31", nightly: 140 },
        { label: "High Season", from: "2026-06-01", to: "2026-09-30", nightly: 220 },
      ],
      unavailableDates: [],
    },
    amenities: ["Wi-Fi", "Air Conditioning", "Courtyard", "Rooftop Terrace", "Washing Machine", "Fully Equipped Kitchen"],
    highlights: ["Venetian harbor views", "Walking distance to port", "Restored original stonework", "Strong rental yield"],
    badges: ["Investment Pick"],
    policies: { smokingAllowed: false, petsAllowed: false, cancellationSummary: "Free cancellation up to 30 days before check-in.", tourismLicense: "MHTE 10.28.901" },
    nearby: [
      { label: "Venetian Port", value: "200 m" },
      { label: "Airport (CHQ)", value: "15 km" },
      { label: "Market", value: "100 m" },
    ],
    faqs: [
      { q: "Is financing available for purchase?", a: "We can connect you with local mortgage advisors for EU residents." },
      { q: "What is the expected rental yield?", a: "Properties in this area see 6-8% gross yield on short-term rentals." },
    ],
    related: [],
    nearbyServices: [],
    blogPosts: [],
    realEstateMeta: {
      salePriceEur: 385000,
      monthlyRentEur: 1800,
      roiPercent: 7.2,
      saleHighlights: ["Prime Old Town location", "Fully renovated 2024", "Tourism license active"],
      monthlyHighlights: ["Furnished and ready", "Bills included option", "Long-term discount available"],
    },
  },
  {
    id: "ct-p-003",
    slug: "seaside-apartment-corfu",
    title: "Seaside Apartment Corfu",
    headline: "Modern Beachfront Apartment in Corfu Town",
    shortDescription: "Bright 2-bedroom apartment with direct beach access and Ionian Sea views.",
    detailDescription: "A modern, fully furnished apartment on the seafront of Corfu Town. Open-plan living with large balcony overlooking the Ionian Sea. Perfect for couples or small families seeking a comfortable base to explore Corfu.",
    type: "vacation",
    dealTypes: ["short_term_rent"],
    status: "active",
    location: { area: "Corfu Town", region: "Corfu", country: "Greece", beachDistanceM: 50, lat: 39.624, lng: 19.922 },
    metrics: { guests: 4, bedrooms: 2, bathrooms: 1, areaSqm: 85 },
    gallery: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=1600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=1600&auto=format&fit=crop",
    ],
    pricing: {
      currency: "EUR",
      basicFromPrice: 120,
      seasonalFromPrice: 190,
      seasonName: "Peak Summer",
      minStayNights: 2,
      seasonalRates: [
        { label: "Off Season", from: "2026-10-01", to: "2026-04-30", nightly: 120 },
        { label: "Peak Summer", from: "2026-07-01", to: "2026-08-31", nightly: 190 },
      ],
      unavailableDates: [],
    },
    amenities: ["Wi-Fi", "Air Conditioning", "Balcony", "Sea View", "Parking", "Washing Machine"],
    highlights: ["Direct beach access", "Sea-view balcony", "Central Corfu Town location"],
    badges: ["Beach Access"],
    policies: { smokingAllowed: false, petsAllowed: false, cancellationSummary: "Free cancellation up to 7 days before check-in.", tourismLicense: "MHTE 04.12.345" },
    nearby: [
      { label: "Beach", value: "50 m" },
      { label: "Airport (CFU)", value: "3 km" },
      { label: "Old Fortress", value: "800 m" },
    ],
    faqs: [
      { q: "Is parking included?", a: "Yes, one private parking spot is included." },
    ],
    related: [
      { title: "Villa Azure Halkidiki", href: "/property/vacation/villa-azure-halkidiki", from: 180, image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?q=80&w=800&auto=format&fit=crop" },
    ],
    nearbyServices: [],
    blogPosts: [],
  },
];
