import type { Tool } from "./types";

export const TOOLS: Tool[] = [
  // ── Phase 1 Flagship Tools ──
  {
    slug: "ai-description-assistant",
    name: "AI Description Assistant",
    tagline: "Generate compelling property descriptions in seconds",
    description: "Use AI to create professional, SEO-optimized property descriptions in multiple languages. Input property specs and photos — get polished listings ready for Airbnb, Booking.com, and your own website.",
    category: "creation",
    status: "active",
    roles: ["owner", "pmc"],
    primaryRole: "owner",
    icon: "pencil",
    color: "violet",
    hasDemo: true,
    demoMode: "sandbox",
    features: [
      "AI-powered property description generation",
      "Multi-language output (EN, GR, DE, FR, RU)",
      "SEO-optimized for OTA platforms",
      "Tone control (luxury, family, budget, romantic)",
      "Bulk generation for multiple properties",
      "One-click copy to clipboard",
    ],
    useCases: [
      { role: "Owners", cases: ["Create your first listing description", "Refresh old listings with modern copy", "Generate descriptions for new platforms"] },
      { role: "PMCs", cases: ["Bulk-generate descriptions for portfolio", "Maintain consistent brand voice", "A/B test different description styles"] },
    ],
    inputs: ["Property type, location, amenities", "Number of bedrooms/bathrooms", "Unique selling points", "Target audience/tone"],
    outputs: ["Formatted description text", "SEO meta description", "Platform-specific versions (Airbnb, Booking.com)"],
    integrations: ["Copy to clipboard", "Export as PDF", "Future: direct OTA push"],
    faq: [
      { q: "What languages are supported?", a: "English, Greek, German, French, and Russian. More languages coming soon." },
      { q: "Can I edit the generated text?", a: "Yes, all generated descriptions are fully editable before publishing." },
      { q: "Does it work for commercial properties?", a: "Yes — works for villas, apartments, hotels, commercial spaces, and land." },
    ],
  },
  {
    slug: "investment-analyzer",
    name: "Investment Analyzer",
    tagline: "Calculate ROI on Greek property investments",
    description: "Comprehensive investment analysis tool for Greek real estate. Input purchase price, renovation costs, and rental projections — get detailed ROI calculations, cash flow analysis, and break-even timelines.",
    category: "calculator",
    status: "active",
    roles: ["owner"],
    primaryRole: "owner",
    icon: "chart",
    color: "emerald",
    hasDemo: true,
    demoMode: "sandbox",
    features: [
      "Purchase price + renovation cost modeling",
      "Seasonal rental income projections",
      "Tax estimation (Greek property tax framework)",
      "Cash flow analysis (monthly/yearly)",
      "Break-even timeline calculator",
      "Compare multiple investment scenarios",
      "Export professional PDF report",
    ],
    useCases: [
      { role: "Owners", cases: ["Evaluate buying a vacation rental property", "Compare renovation ROI options", "Plan pricing strategy based on target returns"] },
    ],
    inputs: ["Purchase price", "Renovation budget", "Expected nightly rate", "Occupancy estimate", "Annual expenses"],
    outputs: ["ROI percentage", "Monthly cash flow", "Break-even date", "PDF investment report"],
    faq: [
      { q: "Are tax calculations accurate?", a: "We use current Greek property tax rates as estimates. Consult a tax advisor for exact obligations." },
      { q: "Can I compare multiple properties?", a: "Yes — run side-by-side analysis for up to 3 investment scenarios." },
    ],
  },
  {
    slug: "trip-cost-calculator",
    name: "Trip Cost Calculator",
    tagline: "Plan your Greece vacation budget in minutes",
    description: "Interactive budget planner for Greece trips. Select destination, dates, group size, and accommodation style — get a detailed cost breakdown including flights, accommodation, food, activities, and transport.",
    category: "calculator",
    status: "active",
    roles: ["guest"],
    primaryRole: "guest",
    icon: "calculator",
    color: "cyan",
    hasDemo: true,
    demoMode: "sandbox",
    features: [
      "Destination-specific pricing data",
      "Seasonal price adjustments",
      "Group size scaling (1-20 people)",
      "Accommodation tier options (budget/mid/luxury)",
      "Activity and excursion estimates",
      "Transport cost calculator (car rental, ferries, flights)",
      "Shareable budget summary link",
    ],
    useCases: [
      { role: "Guests", cases: ["Plan family vacation budget", "Compare costs between Greek islands", "Estimate group trip expenses", "Share budget with travel companions"] },
    ],
    inputs: ["Destination", "Travel dates", "Group size", "Accommodation preference", "Activity interests"],
    outputs: ["Detailed cost breakdown", "Daily budget estimate", "Shareable summary link", "PDF budget report"],
    faq: [
      { q: "How accurate are the estimates?", a: "Based on real market data from Greek tourism operators. Actual costs may vary by 10-20%." },
      { q: "Does it include flight costs?", a: "It estimates average flight costs from major European cities. You can customize the origin." },
    ],
  },
  {
    slug: "custom-quote-generator",
    name: "Custom Quote Generator",
    tagline: "Create professional pricing quotes in seconds",
    description: "Build and send branded pricing quotes for properties, services, or packages. Drag-and-drop line items, apply seasonal pricing rules, add photos and terms — generate a shareable quote link or PDF.",
    category: "creation",
    status: "active",
    roles: ["pmc", "agent"],
    primaryRole: "pmc",
    icon: "document",
    color: "amber",
    hasDemo: true,
    demoMode: "guidedTour",
    features: [
      "Drag-and-drop quote builder",
      "Seasonal pricing rules engine",
      "Branded templates (logo, colors, fonts)",
      "Multi-currency support (EUR, USD, GBP)",
      "Shareable quote link with expiry",
      "PDF export with professional layout",
      "Quote tracking (viewed, accepted, expired)",
    ],
    useCases: [
      { role: "PMCs", cases: ["Send owner management proposals", "Generate guest booking quotes", "Create seasonal rate cards"] },
      { role: "Agents", cases: ["Build client vacation packages", "Quote group bookings", "Generate branded offer sheets"] },
    ],
    inputs: ["Property/service selection", "Dates and duration", "Guest count", "Add-on services", "Custom line items"],
    outputs: ["Interactive quote page", "PDF download", "Shareable link", "Email-ready format"],
    faq: [
      { q: "Can clients accept quotes online?", a: "Yes — quote links include an 'Accept' button that notifies you instantly." },
      { q: "Can I add my own branding?", a: "Yes — upload your logo and set brand colors for all generated quotes." },
    ],
  },
  {
    slug: "photo-optimizer",
    name: "Photo Optimizer + Watermark",
    tagline: "Enhance property photos and add branded watermarks",
    description: "Batch-optimize property photos for web and OTA platforms. Auto-enhance lighting and colors, resize for platform requirements, and add branded watermarks — all in one step.",
    category: "optimization",
    status: "active",
    roles: ["owner", "pmc", "serviceProvider"],
    primaryRole: "pmc",
    icon: "camera",
    color: "sky",
    hasDemo: true,
    demoMode: "sandbox",
    features: [
      "AI-powered auto-enhancement (brightness, contrast, saturation)",
      "Batch processing (up to 50 photos)",
      "Platform-specific resizing (Airbnb, Booking.com, Google)",
      "Custom watermark placement (logo, text, opacity)",
      "EXIF data cleanup for privacy",
      "Before/after comparison slider",
      "Download as ZIP or individual files",
    ],
    useCases: [
      { role: "Owners", cases: ["Enhance listing photos before publishing", "Add watermark to protect images", "Resize for different platforms"] },
      { role: "PMCs", cases: ["Batch-process entire property portfolios", "Apply consistent branding across all listings", "Prepare photos for marketing materials"] },
      { role: "Service Providers", cases: ["Enhance service portfolio images", "Watermark promotional photos", "Optimize images for website and social"] },
    ],
    inputs: ["Property photos (JPEG, PNG, WebP)", "Watermark image/text", "Target platforms", "Enhancement preferences"],
    outputs: ["Optimized photos", "Watermarked versions", "ZIP download", "Platform-ready crops"],
    faq: [
      { q: "What's the maximum file size?", a: "Up to 20MB per image, 50 images per batch." },
      { q: "Will it reduce image quality?", a: "Enhancement improves visual quality. Compression is optimized to maintain clarity while reducing file size." },
    ],
  },

  // ── Phase 1 Additional (from Confluence, as coming soon) ──
  {
    slug: "auto-video-generator",
    name: "Auto Video Generator",
    tagline: "Create YouTube property videos from your photos",
    description: "Automatically generate professional property tour videos from your photos. Add music, transitions, text overlays, and branding — ready to upload to YouTube and social media.",
    category: "creation",
    status: "comingSoon",
    roles: ["pmc", "agent"],
    icon: "video",
    color: "red",
    hasDemo: false,
    features: ["Photo-to-video conversion", "Music library", "Text overlays", "Brand watermark", "YouTube-ready export"],
    useCases: [{ role: "PMCs", cases: ["Create virtual property tours", "Generate social media content"] }],
  },
  {
    slug: "whatsapp-share-tool",
    name: "WhatsApp Share Tool",
    tagline: "Share property links with one click via WhatsApp",
    description: "Generate and share beautifully formatted property links, quotes, and availability info directly through WhatsApp. Includes preview cards and tracking.",
    category: "distribution",
    status: "comingSoon",
    roles: ["pmc", "agent", "serviceProvider"],
    icon: "share",
    color: "green",
    hasDemo: false,
    features: ["One-click WhatsApp sharing", "Rich link previews", "Click tracking", "Bulk send lists"],
    useCases: [{ role: "Agents", cases: ["Share property options with clients", "Send booking confirmations"] }],
  },
  {
    slug: "client-proposal-builder",
    name: "Client Proposal Builder",
    tagline: "Build professional proposals that close deals",
    description: "Create stunning client proposals with property details, pricing, photos, and terms. Track when proposals are viewed and accepted.",
    category: "creation",
    status: "comingSoon",
    roles: ["agent", "pmc"],
    icon: "briefcase",
    color: "indigo",
    hasDemo: false,
    features: ["Drag-and-drop proposal builder", "Branded templates", "View tracking", "E-signature ready", "PDF export"],
    useCases: [{ role: "Agents", cases: ["Present vacation packages", "Propose real estate deals", "Bundle services for groups"] }],
  },
  {
    slug: "lead-form-generator",
    name: "Lead Form Generator + CRM Export",
    tagline: "Create custom lead forms with CRM integration",
    description: "Build custom lead capture forms with drag-and-drop. Embed on your website or share as links. Auto-export leads to your CRM or spreadsheet.",
    category: "system",
    status: "comingSoon",
    roles: ["pmc", "serviceProvider"],
    icon: "form",
    color: "orange",
    hasDemo: false,
    features: ["Drag-and-drop form builder", "Embeddable widgets", "CRM auto-export", "Lead scoring", "Notification rules"],
    useCases: [{ role: "PMCs", cases: ["Capture owner inquiries", "Build guest mailing lists"] }],
  },
  {
    slug: "review-management-dashboard",
    name: "Review Management Dashboard",
    tagline: "Monitor and respond to reviews across all platforms",
    description: "Aggregate reviews from Airbnb, Booking.com, Google, and TripAdvisor in one dashboard. Get alerts, generate AI-powered responses, and track sentiment trends.",
    category: "insights",
    status: "comingSoon",
    roles: ["owner", "pmc", "serviceProvider", "all"],
    icon: "star",
    color: "yellow",
    hasDemo: false,
    features: ["Multi-platform review aggregation", "AI response suggestions", "Sentiment analysis", "Alert system", "Trend reports"],
    useCases: [{ role: "Owners", cases: ["Monitor property reviews", "Respond quickly to negative feedback"] }],
  },
  {
    slug: "bulk-listing-importer",
    name: "Bulk Listing Importer",
    tagline: "Import property listings from CSV or API in bulk",
    description: "Bulk-import properties from spreadsheets, channel managers, or API feeds. Map fields, validate data, and publish listings across ClickyTour ecosystem.",
    category: "system",
    status: "comingSoon",
    roles: ["pmc"],
    icon: "upload",
    color: "slate",
    hasDemo: false,
    features: ["CSV/Excel import", "Field mapping wizard", "Validation checks", "Duplicate detection", "API feed support"],
    useCases: [{ role: "PMCs", cases: ["Migrate portfolio from another platform", "Sync from channel manager"] }],
  },
  {
    slug: "service-bundler",
    name: "Service Bundler Tool",
    tagline: "Package multiple services into sellable bundles",
    description: "Combine multiple services (cleaning + transfers + activities) into branded packages with bundled pricing. Perfect for upselling and cross-selling.",
    category: "creation",
    status: "comingSoon",
    roles: ["serviceProvider"],
    icon: "package",
    color: "teal",
    hasDemo: false,
    features: ["Drag-and-drop bundle builder", "Bundle pricing rules", "Branded package pages", "Shareable bundle links"],
    useCases: [{ role: "Service Providers", cases: ["Create welcome packages", "Bundle seasonal activities", "Cross-sell related services"] }],
  },
  // ── Phase T1: Missing Confluence Tools ──
  {
    slug: "agent-quotation-builder",
    name: "Agent Quotation Builder",
    tagline: "Build branded quotations for vacation & real estate clients",
    description: "Create professional, branded quotations for property rentals, sales, and service packages. Include property photos, pricing breakdowns, terms, and seasonal rates — send as a shareable link or PDF.",
    category: "creation",
    status: "comingSoon",
    roles: ["agent"],
    primaryRole: "agent",
    icon: "document",
    color: "indigo",
    hasDemo: false,
    features: [
      "Branded quotation templates",
      "Property photo integration",
      "Seasonal pricing breakdowns",
      "Multi-property comparison quotes",
      "Shareable link with expiry tracking",
      "PDF export with e-signature field",
    ],
    useCases: [
      { role: "Agents", cases: ["Quote vacation rental packages for clients", "Present real estate purchase offers", "Bundle properties + services in one quote"] },
    ],
    inputs: ["Property selection", "Date range", "Guest count", "Add-on services", "Agent branding"],
    outputs: ["Interactive quotation page", "PDF download", "Shareable tracking link"],
    faq: [
      { q: "How is this different from Custom Quote Generator?", a: "Agent Quotation Builder is designed specifically for agents with multi-property comparison and commission tracking built in." },
    ],
  },
  {
    slug: "no-logo-presentation",
    name: "No Logo Presentation Tool",
    tagline: "Create unbranded property presentations for anonymous sharing",
    description: "Generate clean, professional property presentations without any agency or platform branding. Perfect for sharing with new leads before revealing your identity — powered by PickedFor.",
    category: "creation",
    status: "comingSoon",
    roles: ["pmc", "agent"],
    primaryRole: "pmc",
    icon: "document",
    color: "slate",
    hasDemo: false,
    features: [
      "Zero-branding property presentations",
      "Professional photo gallery layout",
      "Pricing and availability display",
      "Shareable anonymous link",
      "Lead capture on view",
      "Reveal branding after engagement",
    ],
    useCases: [
      { role: "PMCs", cases: ["Share properties with unregistered leads", "A/B test branded vs unbranded conversions", "Protect portfolio from competitors"] },
      { role: "Agents", cases: ["Present options without revealing source", "Share with clients before formal agreement", "Use as marketing funnel entry point"] },
    ],
    faq: [
      { q: "Where are presentations hosted?", a: "Presentations are hosted on PickedFor (pickedfor.com) for maximum anonymity." },
    ],
  },
  {
    slug: "performance-dashboard",
    name: "Performance Dashboard",
    tagline: "Track listings, bookings, and revenue in real time",
    description: "Unified dashboard showing key performance metrics across all your properties and services. Track views, inquiries, bookings, revenue, and occupancy — with trend analysis and alerts.",
    category: "insights",
    status: "comingSoon",
    roles: ["owner", "pmc", "agent"],
    icon: "chart",
    color: "blue",
    hasDemo: false,
    features: [
      "Real-time KPI cards (views, inquiries, bookings, revenue)",
      "Property-level performance breakdown",
      "Seasonal trend analysis",
      "Occupancy rate tracking",
      "Revenue forecasting",
      "Custom alert thresholds",
      "Exportable reports (PDF, CSV)",
    ],
    useCases: [
      { role: "Owners", cases: ["Monitor property performance", "Compare seasonal revenue", "Track occupancy trends"] },
      { role: "PMCs", cases: ["Portfolio-wide performance overview", "Identify underperforming listings", "Generate owner reports"] },
      { role: "Agents", cases: ["Track commission earnings", "Monitor booking pipeline", "Analyze client conversion rates"] },
    ],
  },
  {
    slug: "white-label-microsite",
    name: "White-label Microsite Builder",
    tagline: "Create your own branded property website in minutes",
    description: "Build a fully branded microsite for your property portfolio. Custom domain, logo, colors, and content — powered by ClickyTour infrastructure but appearing as your own website.",
    category: "creation",
    status: "comingSoon",
    roles: ["pmc", "agent"],
    icon: "briefcase",
    color: "purple",
    hasDemo: false,
    features: [
      "Custom domain support",
      "Brand customization (logo, colors, fonts)",
      "Property listing pages auto-synced",
      "Booking widget integration",
      "SEO-optimized templates",
      "Contact form with CRM routing",
    ],
    useCases: [
      { role: "PMCs", cases: ["Launch branded portfolio website", "Provide direct booking channel", "Reduce OTA dependency"] },
      { role: "Agents", cases: ["Create professional agency website", "Showcase curated property collections", "Build client-facing portal"] },
    ],
  },
  {
    slug: "instant-booking-payment-link",
    name: "Instant Booking Payment Link Generator",
    tagline: "Generate secure payment links for instant bookings",
    description: "Create and send secure payment links for property bookings. Supports deposits, full payments, and split payments — with automatic confirmation and receipt generation.",
    category: "distribution",
    status: "comingSoon",
    roles: ["pmc"],
    primaryRole: "pmc",
    icon: "share",
    color: "emerald",
    hasDemo: false,
    features: [
      "Secure payment link generation",
      "Deposit and full payment options",
      "Split payment support",
      "Automatic booking confirmation",
      "Receipt and invoice generation",
      "Multi-currency (EUR, USD, GBP)",
    ],
    useCases: [
      { role: "PMCs", cases: ["Collect deposits for direct bookings", "Send payment requests via WhatsApp/email", "Automate booking confirmation flow"] },
    ],
  },
  {
    slug: "social-media-post-generator",
    name: "Automated Social Media Post Generator",
    tagline: "Create and schedule property posts for social media",
    description: "Auto-generate engaging social media posts from your property listings. Supports Instagram, Facebook, and Pinterest — with hashtag optimization, scheduling, and multi-language captions.",
    category: "distribution",
    status: "comingSoon",
    roles: ["pmc", "serviceProvider"],
    icon: "share",
    color: "pink",
    hasDemo: false,
    features: [
      "Auto-generate posts from listings",
      "Platform-specific formatting (IG, FB, Pinterest)",
      "Hashtag optimization",
      "Multi-language captions",
      "Scheduling and auto-publish",
      "Performance tracking per post",
    ],
    useCases: [
      { role: "PMCs", cases: ["Automate property promotion", "Maintain consistent social presence", "Drive direct booking traffic"] },
      { role: "Service Providers", cases: ["Promote services on social media", "Share client testimonials", "Boost seasonal offers"] },
    ],
  },
  {
    slug: "click-to-quote-link",
    name: "Click-to-Quote Link Generator",
    tagline: "Generate shareable links that open pre-filled quote requests",
    description: "Create smart links that, when clicked, open a pre-filled quote request form for a specific property or service. Embed in emails, ads, or social — track clicks and conversions.",
    category: "distribution",
    status: "comingSoon",
    roles: ["agent"],
    primaryRole: "agent",
    icon: "share",
    color: "orange",
    hasDemo: false,
    features: [
      "Pre-filled quote request links",
      "Embeddable in email/ads/social",
      "Click and conversion tracking",
      "Custom landing page per link",
      "UTM parameter support",
    ],
    useCases: [
      { role: "Agents", cases: ["Add quote links to email campaigns", "Track ad-to-quote conversion", "Create property-specific inquiry links"] },
    ],
  },
  {
    slug: "multilingual-flyer-generator",
    name: "Multilingual Flyer/PDF Generator",
    tagline: "Create print-ready property flyers in any language",
    description: "Generate professional property flyers and PDF brochures in multiple languages. Choose from templates, add photos and details, and download print-ready files or shareable links.",
    category: "creation",
    status: "comingSoon",
    roles: ["pmc", "serviceProvider"],
    icon: "document",
    color: "rose",
    hasDemo: false,
    features: [
      "Professional flyer templates",
      "Multi-language generation (EN, GR, DE, FR, RU)",
      "Print-ready PDF export (A4, A5, Letter)",
      "QR code integration",
      "Photo layout options",
      "Shareable digital version link",
    ],
    useCases: [
      { role: "PMCs", cases: ["Create lobby/reception property flyers", "Generate multilingual brochures for international guests", "Distribute at travel expos"] },
      { role: "Service Providers", cases: ["Print service menus for hotels", "Create activity brochures", "Generate seasonal offer flyers"] },
    ],
  },
  {
    slug: "visibility-boost",
    name: "Visibility Boost Tool",
    tagline: "Boost your listing visibility across ClickyTour ecosystem",
    description: "Promote your listing to premium positions in search results, directory pages, and homepage features. Choose boost duration, target audience, and budget — track impressions and clicks in real time.",
    category: "optimization",
    status: "comingSoon",
    roles: ["pmc", "serviceProvider"],
    icon: "star",
    color: "amber",
    hasDemo: false,
    features: [
      "Featured listing placement",
      "Search result priority boost",
      "Homepage spotlight slots",
      "Target by region/category",
      "Real-time impression/click tracking",
      "Budget control and scheduling",
    ],
    useCases: [
      { role: "PMCs", cases: ["Boost new property listings", "Increase visibility during peak season", "Promote special offers"] },
      { role: "Service Providers", cases: ["Stand out in service directories", "Promote seasonal activities", "Target specific regions"] },
    ],
  },

  // ── HIGH PRIORITY Interactive Tools ──
  {
    slug: "occupancy-heatmap",
    name: "Seasonal Occupancy Heatmap",
    tagline: "Visualize booking patterns and optimize your pricing calendar",
    description: "Interactive monthly heatmap showing occupancy rates for 12 Greek regions. Get suggested nightly rates, annual revenue projections, pricing gap analysis, and seasonal optimization advice based on real market data.",
    category: "insights",
    status: "active",
    roles: ["owner", "pmc", "agent"],
    primaryRole: "owner",
    icon: "chart",
    color: "amber",
    hasDemo: true,
    demoMode: "sandbox",
    features: ["12 Greek regions with monthly occupancy data", "Dynamic nightly rate suggestions", "Annual revenue projection", "Pricing gap identification", "Greek events & holidays overlay", "Compare your rate vs suggested pricing"],
    useCases: [
      { role: "Owners", cases: ["Identify underpriced months", "Plan seasonal pricing strategy", "Maximize annual revenue"] },
      { role: "PMCs", cases: ["Portfolio-wide seasonal analysis", "Justify pricing to owners", "Identify promotion opportunities"] },
    ],
    inputs: ["Region", "Bedrooms", "Current base rate (optional)"],
    outputs: ["Monthly occupancy heatmap", "Suggested rates per month", "Annual revenue estimate", "Pricing gap alerts"],
  },
  {
    slug: "guest-guidebook",
    name: "Guest Digital Guidebook",
    tagline: "Create beautiful, multilingual property guidebooks guests access on their phone",
    description: "Build digital guidebooks with check-in instructions, house rules, WiFi info, local recommendations, and emergency contacts. Choose from 4 Greek-inspired themes, select languages, and preview on a phone mockup. No app needed — guests access via QR code.",
    category: "creation",
    status: "active",
    roles: ["pmc", "owner"],
    primaryRole: "pmc",
    icon: "document",
    color: "sky",
    hasDemo: true,
    demoMode: "sandbox",
    features: ["14 customizable content sections", "6 language options", "4 Greek-themed designs", "Phone preview mockup", "QR code generation", "Section toggle and editing", "Shareable web link"],
    useCases: [
      { role: "PMCs", cases: ["Create standardized guidebooks for portfolio", "Reduce guest questions by 70%", "Upsell local services via recommendations"] },
      { role: "Owners", cases: ["Professional welcome experience", "Multilingual support for international guests", "Easy updates without reprinting"] },
    ],
    inputs: ["Property name", "Section content", "Language selection", "Theme choice"],
    outputs: ["Digital guidebook", "QR code", "Shareable link", "PDF export"],
  },
  {
    slug: "review-response-generator",
    name: "AI Review Response Generator",
    tagline: "Generate professional, personalized review responses in seconds",
    description: "Smart template engine that creates contextual review responses based on sentiment (positive/mixed/negative), tone (professional/warm/casual/luxury), and specific praise or issue topics. One-click copy to clipboard.",
    category: "optimization",
    status: "active",
    roles: ["owner", "pmc"],
    primaryRole: "pmc",
    icon: "star",
    color: "yellow",
    hasDemo: true,
    demoMode: "sandbox",
    features: ["3 sentiment levels (positive/mixed/negative)", "4 tone options", "13 common issues to address", "13 praise topics to highlight", "One-click copy to clipboard", "Response best practices guide"],
    useCases: [
      { role: "Owners", cases: ["Respond to reviews faster", "Maintain professional tone consistently", "Handle negative reviews gracefully"] },
      { role: "PMCs", cases: ["Scale review management across portfolio", "Train team on response standards", "Improve response time metrics"] },
    ],
    inputs: ["Guest name", "Review sentiment", "Tone preference", "Specific praises/issues"],
    outputs: ["Ready-to-post review response", "Copy to clipboard"],
  },
  {
    slug: "contract-generator",
    name: "Smart Contract / Lease Generator",
    tagline: "Generate Greek-compliant rental agreements and management contracts instantly",
    description: "Template-based contract generator for 4 contract types: short-term rental, long-term lease, property management, and service agreements. Pre-filled with Greek legal requirements (AADE registration, governing law), customizable clauses, and preview/copy/export.",
    category: "creation",
    status: "active",
    roles: ["pmc", "owner", "agent"],
    primaryRole: "pmc",
    icon: "document",
    color: "indigo",
    hasDemo: true,
    demoMode: "sandbox",
    features: ["4 contract types", "Greek legal compliance (AADE, Civil Code)", "Required + optional clause toggles", "Full contract preview", "Copy to clipboard", "Party and property details prefill"],
    useCases: [
      { role: "PMCs", cases: ["Generate management contracts for new owners", "Standard rental agreements for guests", "Service provider agreements for vendors"] },
      { role: "Owners", cases: ["Create rental agreements for direct bookings", "Long-term lease contracts", "Understand Greek legal requirements"] },
    ],
    inputs: ["Contract type", "Party names", "Property address", "Clause selection"],
    outputs: ["Complete contract document", "Plain text copy", "PDF export (coming soon)"],
  },
  {
    slug: "expense-tracker",
    name: "Expense Tracker & Accounting",
    tagline: "Track property expenses, generate tax reports, and manage finances",
    description: "Multi-property expense tracking with 11 categories, filtering, tax deduction estimates, and financial insights. Add expenses, view by property or category, and see net profit after expenses with Greek tax saving estimates.",
    category: "insights",
    status: "active",
    roles: ["owner", "pmc"],
    primaryRole: "owner",
    icon: "chart",
    color: "emerald",
    hasDemo: true,
    demoMode: "sandbox",
    features: ["11 expense categories", "Multi-property tracking", "Category and property filtering", "Tax deduction estimates (22% rate)", "Net profit calculation", "Expense ratio analysis", "Add/remove expenses in real-time"],
    useCases: [
      { role: "Owners", cases: ["Track all property costs in one place", "Prepare for Greek tax filing", "Understand expense patterns"] },
      { role: "PMCs", cases: ["Track expenses across portfolio", "Generate owner expense reports", "Optimize operational costs"] },
    ],
    inputs: ["Expense details (date, category, amount, property)", "Annual revenue for ratio"],
    outputs: ["Expense list with totals", "Category breakdown", "Tax saving estimate", "Net profit"],
  },

  // ── Quick-Win Calculators (from Future Tools Research) ──
  {
    slug: "golden-visa-calculator",
    name: "Golden Visa Investment Calculator",
    tagline: "Explore Greece Golden Visa eligibility, costs, and ROI by region",
    description: "Interactive tool showing Golden Visa thresholds by zone (250K/400K/800K), eligible property types, residency timeline, total acquisition costs, rental income projections, and investment ROI over your chosen hold period. Includes family member cost splitting and residency benefits overview.",
    category: "calculator",
    status: "active",
    roles: ["owner", "guest"],
    primaryRole: "guest",
    icon: "calculator",
    color: "emerald",
    hasDemo: true,
    demoMode: "sandbox",
    features: [
      "Zone-based threshold mapping (15 Greek regions)",
      "Total acquisition cost breakdown (taxes, legal, notary, agent)",
      "Rental income projections (STR vs LTR vs personal use)",
      "Multi-year ROI and appreciation forecast",
      "Family member cost splitting",
      "Golden Visa eligibility check",
      "Residency benefits overview",
      "Mortgage scenario modeling",
    ],
    useCases: [
      { role: "Investors", cases: ["Evaluate Golden Visa investment zones", "Compare ROI across Greek regions", "Calculate total cost including closing fees"] },
      { role: "Owners", cases: ["Understand property value in Golden Visa context", "Estimate rental returns on investment property"] },
    ],
    inputs: ["Investment zone", "Property value", "Property size", "Rental strategy", "Family members", "Hold period"],
    outputs: ["Eligibility status", "Total acquisition cost", "Annual rental income", "Multi-year ROI", "Per-member cost"],
    faq: [
      { q: "Are the Golden Visa thresholds up to date?", a: "Based on 2026 thresholds. Greece updates rules periodically — consult an immigration lawyer for current requirements." },
      { q: "Can I combine multiple properties?", a: "Yes, in some zones you can combine properties to meet the threshold. This calculator shows per-property analysis." },
    ],
  },
  {
    slug: "ferry-island-planner",
    name: "Ferry & Island Hopping Planner",
    tagline: "Plan multi-island itineraries with ferry routes and cost estimates",
    description: "Interactive island-hopping planner for Greece with 18 islands, 5 departure ports, inter-island ferry routes, accommodation estimates, and total trip cost breakdown. Select your islands, set nights per stop, and get a complete budget.",
    category: "calculator",
    status: "active",
    roles: ["guest"],
    primaryRole: "guest",
    icon: "calculator",
    color: "blue",
    hasDemo: true,
    demoMode: "sandbox",
    features: [
      "18 Greek islands across 6 island groups",
      "5 mainland departure ports",
      "Inter-island ferry route mapping",
      "Duration and cost per leg",
      "Accommodation estimates by style and season",
      "Food & dining budget included",
      "Per-person and per-day cost breakdown",
      "Seasonal pricing adjustments",
    ],
    useCases: [
      { role: "Guests", cases: ["Plan a Cyclades island-hopping trip", "Budget a family Greek island vacation", "Compare costs between island groups"] },
    ],
    inputs: ["Departure port", "Islands to visit", "Nights per island", "Travelers", "Season", "Accommodation style"],
    outputs: ["Total trip cost", "Ferry route with durations", "Accommodation breakdown", "Cost per person/day"],
    faq: [
      { q: "Are ferry prices accurate?", a: "Estimates based on 2025-2026 averages. Check ferryhopper.com for real-time schedules and exact pricing." },
      { q: "Can I reorder islands?", a: "Islands are visited in the order you select them. Remove and re-add to change order." },
    ],
  },
  {
    slug: "property-valuation",
    name: "Property Valuation Estimator",
    tagline: "Get an instant property value estimate for Greek real estate",
    description: "AI-powered property valuation based on location, size, type, condition, year built, floor, and amenities. Covers 18 Greek regions with market data, rental yield estimates, and Golden Visa eligibility check.",
    category: "calculator",
    status: "active",
    roles: ["owner", "guest"],
    primaryRole: "owner",
    icon: "chart",
    color: "violet",
    hasDemo: true,
    demoMode: "sandbox",
    features: [
      "18 Greek regions with market price data",
      "6 property types with adjusted multipliers",
      "Condition, age, and floor adjustments",
      "8 feature toggles (pool, sea view, parking, etc.)",
      "Value range estimation (low-high)",
      "Monthly rental income estimate",
      "Market demand indicator",
      "Golden Visa eligibility check",
    ],
    useCases: [
      { role: "Owners", cases: ["Estimate current property value", "Understand impact of renovations on value", "Compare value across regions"] },
      { role: "Investors", cases: ["Screen properties before site visit", "Compare investment opportunities", "Check Golden Visa eligibility"] },
    ],
    inputs: ["Location", "Property type", "Condition", "Size (m2)", "Bedrooms", "Year built", "Floor", "Features"],
    outputs: ["Estimated value", "Value range", "Price per m2", "Monthly rental estimate", "Market demand", "Golden Visa status"],
    faq: [
      { q: "How accurate is the valuation?", a: "Estimates are based on regional averages and may vary 15-25% from actual market value. For accurate valuations, consult a licensed Greek appraiser." },
      { q: "Does it account for exact location?", a: "It uses regional averages. Street-level factors (proximity to sea, views, noise) are approximated through the features toggles." },
    ],
  },

  {
    slug: "commission-calculator",
    name: "Commission Calculator",
    tagline: "Calculate your agent earnings per booking",
    description: "Instantly calculate commission earnings based on booking value, property type, and partnership tier. Compare scenarios and project annual income.",
    category: "calculator",
    status: "active",
    roles: ["agent"],
    primaryRole: "agent",
    icon: "calculator",
    color: "indigo",
    hasDemo: true,
    demoMode: "sandbox",
    features: ["Real-time commission calculation", "Multi-tier support", "Annual income projections", "Scenario comparison", "Export earnings report"],
    useCases: [{ role: "Agents", cases: ["Estimate earnings from new partnerships", "Compare commission structures", "Project seasonal income"] }],
    inputs: ["Booking value", "Commission tier", "Property type", "Number of bookings"],
    outputs: ["Commission amount", "Annual projection", "PDF report"],
  },
  {
    slug: "rental-income-estimator",
    name: "Rental Income Estimator",
    tagline: "Estimate your vacation rental income by region",
    description: "Compare your property against regional market data. Get estimated nightly rates, occupancy rates, and annual revenue projections based on location, property type, and amenities.",
    category: "calculator",
    status: "active",
    roles: ["owner"],
    primaryRole: "owner",
    icon: "chart",
    color: "emerald",
    hasDemo: true,
    demoMode: "sandbox",
    features: ["Regional market data comparison", "Seasonal rate projections", "Amenity impact analysis", "Revenue optimization tips", "Shareable estimate link"],
    useCases: [{ role: "Owners", cases: ["Evaluate rental potential before listing", "Optimize pricing strategy", "Compare properties across regions"] }],
    inputs: ["Location/region", "Property type", "Bedrooms", "Amenities", "Current rate (optional)"],
    outputs: ["Estimated nightly rate range", "Projected annual revenue", "Occupancy rate estimate", "Market comparison"],
  },
];

export const TOOL_CATEGORIES = [
  { slug: "creation", label: "Creation", icon: "pencil", description: "Content, media, and document generation" },
  { slug: "optimization", label: "Optimization", icon: "sliders", description: "Listings, pricing, and image enhancement" },
  { slug: "distribution", label: "Distribution", icon: "share", description: "Marketing, sharing, and outreach" },
  { slug: "insights", label: "Insights", icon: "chart", description: "Analytics, dashboards, and reporting" },
  { slug: "system", label: "System", icon: "cog", description: "Imports, integrations, and automation" },
  { slug: "calculator", label: "Calculators", icon: "calculator", description: "ROI, budgets, and estimators" },
] as const;

export const TOOL_ROLES = [
  { slug: "owner", label: "Property Owners" },
  { slug: "pmc", label: "Property Managers" },
  { slug: "agent", label: "Agents & Brokers" },
  { slug: "serviceProvider", label: "Service Providers" },
  { slug: "guest", label: "Guests" },
  { slug: "all", label: "All Users" },
] as const;

export function getToolBySlug(slug: string): Tool | undefined {
  return TOOLS.find((t) => t.slug === slug);
}

export function getToolsByRole(role: string): Tool[] {
  return TOOLS.filter((t) => t.roles.includes(role as any) || t.roles.includes("all"));
}

export function getToolsByCategory(category: string): Tool[] {
  return TOOLS.filter((t) => t.category === category);
}

export function getActiveTools(): Tool[] {
  return TOOLS.filter((t) => t.status === "active");
}
