import type { Tool } from "./types";

export const TOOLS: Tool[] = [
  // ── Phase 1 Flagship Tools ──
  {
    slug: "ai-description-assistant",
    name: "AI Description Assistant",
    tagline: "Generate compelling property descriptions in seconds",
    description: "Use AI to create professional, SEO-optimized property descriptions in multiple languages. Input property specs and photos — get polished listings ready for Airbnb, Booking.com, and your own website.",
    category: "creation",
    status: "active",
    roles: ["owner", "pmc"],
    primaryRole: "owner",
    icon: "pencil",
    color: "violet",
    hasDemo: true,
    demoMode: "sandbox",
    features: [
      "AI-powered property description generation",
      "Multi-language output (EN, GR, DE, FR, RU)",
      "SEO-optimized for OTA platforms",
      "Tone control (luxury, family, budget, romantic)",
      "Bulk generation for multiple properties",
      "One-click copy to clipboard",
    ],
    useCases: [
      { role: "Owners", cases: ["Create your first listing description", "Refresh old listings with modern copy", "Generate descriptions for new platforms"] },
      { role: "PMCs", cases: ["Bulk-generate descriptions for portfolio", "Maintain consistent brand voice", "A/B test different description styles"] },
    ],
    inputs: ["Property type, location, amenities", "Number of bedrooms/bathrooms", "Unique selling points", "Target audience/tone"],
    outputs: ["Formatted description text", "SEO meta description", "Platform-specific versions (Airbnb, Booking.com)"],
    integrations: ["Copy to clipboard", "Export as PDF", "Future: direct OTA push"],
    faq: [
      { q: "What languages are supported?", a: "English, Greek, German, French, and Russian. More languages coming soon." },
      { q: "Can I edit the generated text?", a: "Yes, all generated descriptions are fully editable before publishing." },
      { q: "Does it work for commercial properties?", a: "Yes — works for villas, apartments, hotels, commercial spaces, and land." },
    ],
  },
  {
    slug: "investment-analyzer",
    name: "Investment Analyzer",
    tagline: "Calculate ROI on Greek property investments",
    description: "Comprehensive investment analysis tool for Greek real estate. Input purchase price, renovation costs, and rental projections — get detailed ROI calculations, cash flow analysis, and break-even timelines.",
    category: "calculator",
    status: "active",
    roles: ["owner"],
    primaryRole: "owner",
    icon: "chart",
    color: "emerald",
    hasDemo: true,
    demoMode: "sandbox",
    features: [
      "Purchase price + renovation cost modeling",
      "Seasonal rental income projections",
      "Tax estimation (Greek property tax framework)",
      "Cash flow analysis (monthly/yearly)",
      "Break-even timeline calculator",
      "Compare multiple investment scenarios",
      "Export professional PDF report",
    ],
    useCases: [
      { role: "Owners", cases: ["Evaluate buying a vacation rental property", "Compare renovation ROI options", "Plan pricing strategy based on target returns"] },
    ],
    inputs: ["Purchase price", "Renovation budget", "Expected nightly rate", "Occupancy estimate", "Annual expenses"],
    outputs: ["ROI percentage", "Monthly cash flow", "Break-even date", "PDF investment report"],
    faq: [
      { q: "Are tax calculations accurate?", a: "We use current Greek property tax rates as estimates. Consult a tax advisor for exact obligations." },
      { q: "Can I compare multiple properties?", a: "Yes — run side-by-side analysis for up to 3 investment scenarios." },
    ],
  },
  {
    slug: "trip-cost-calculator",
    name: "Trip Cost Calculator",
    tagline: "Plan your Greece vacation budget in minutes",
    description: "Interactive budget planner for Greece trips. Select destination, dates, group size, and accommodation style — get a detailed cost breakdown including flights, accommodation, food, activities, and transport.",
    category: "calculator",
    status: "active",
    roles: ["guest"],
    primaryRole: "guest",
    icon: "calculator",
    color: "cyan",
    hasDemo: true,
    demoMode: "sandbox",
    features: [
      "Destination-specific pricing data",
      "Seasonal price adjustments",
      "Group size scaling (1-20 people)",
      "Accommodation tier options (budget/mid/luxury)",
      "Activity and excursion estimates",
      "Transport cost calculator (car rental, ferries, flights)",
      "Shareable budget summary link",
    ],
    useCases: [
      { role: "Guests", cases: ["Plan family vacation budget", "Compare costs between Greek islands", "Estimate group trip expenses", "Share budget with travel companions"] },
    ],
    inputs: ["Destination", "Travel dates", "Group size", "Accommodation preference", "Activity interests"],
    outputs: ["Detailed cost breakdown", "Daily budget estimate", "Shareable summary link", "PDF budget report"],
    faq: [
      { q: "How accurate are the estimates?", a: "Based on real market data from Greek tourism operators. Actual costs may vary by 10-20%." },
      { q: "Does it include flight costs?", a: "It estimates average flight costs from major European cities. You can customize the origin." },
    ],
  },
  {
    slug: "custom-quote-generator",
    name: "Custom Quote Generator",
    tagline: "Create professional pricing quotes in seconds",
    description: "Build and send branded pricing quotes for properties, services, or packages. Drag-and-drop line items, apply seasonal pricing rules, add photos and terms — generate a shareable quote link or PDF.",
    category: "creation",
    status: "active",
    roles: ["pmc", "agent"],
    primaryRole: "pmc",
    icon: "document",
    color: "amber",
    hasDemo: true,
    demoMode: "guidedTour",
    features: [
      "Drag-and-drop quote builder",
      "Seasonal pricing rules engine",
      "Branded templates (logo, colors, fonts)",
      "Multi-currency support (EUR, USD, GBP)",
      "Shareable quote link with expiry",
      "PDF export with professional layout",
      "Quote tracking (viewed, accepted, expired)",
    ],
    useCases: [
      { role: "PMCs", cases: ["Send owner management proposals", "Generate guest booking quotes", "Create seasonal rate cards"] },
      { role: "Agents", cases: ["Build client vacation packages", "Quote group bookings", "Generate branded offer sheets"] },
    ],
    inputs: ["Property/service selection", "Dates and duration", "Guest count", "Add-on services", "Custom line items"],
    outputs: ["Interactive quote page", "PDF download", "Shareable link", "Email-ready format"],
    faq: [
      { q: "Can clients accept quotes online?", a: "Yes — quote links include an 'Accept' button that notifies you instantly." },
      { q: "Can I add my own branding?", a: "Yes — upload your logo and set brand colors for all generated quotes." },
    ],
  },
  {
    slug: "photo-optimizer",
    name: "Photo Optimizer + Watermark",
    tagline: "Enhance property photos and add branded watermarks",
    description: "Batch-optimize property photos for web and OTA platforms. Auto-enhance lighting and colors, resize for platform requirements, and add branded watermarks — all in one step.",
    category: "optimization",
    status: "active",
    roles: ["owner", "pmc", "serviceProvider"],
    primaryRole: "pmc",
    icon: "camera",
    color: "sky",
    hasDemo: true,
    demoMode: "sandbox",
    features: [
      "AI-powered auto-enhancement (brightness, contrast, saturation)",
      "Batch processing (up to 50 photos)",
      "Platform-specific resizing (Airbnb, Booking.com, Google)",
      "Custom watermark placement (logo, text, opacity)",
      "EXIF data cleanup for privacy",
      "Before/after comparison slider",
      "Download as ZIP or individual files",
    ],
    useCases: [
      { role: "Owners", cases: ["Enhance listing photos before publishing", "Add watermark to protect images", "Resize for different platforms"] },
      { role: "PMCs", cases: ["Batch-process entire property portfolios", "Apply consistent branding across all listings", "Prepare photos for marketing materials"] },
      { role: "Service Providers", cases: ["Enhance service portfolio images", "Watermark promotional photos", "Optimize images for website and social"] },
    ],
    inputs: ["Property photos (JPEG, PNG, WebP)", "Watermark image/text", "Target platforms", "Enhancement preferences"],
    outputs: ["Optimized photos", "Watermarked versions", "ZIP download", "Platform-ready crops"],
    faq: [
      { q: "What's the maximum file size?", a: "Up to 20MB per image, 50 images per batch." },
      { q: "Will it reduce image quality?", a: "Enhancement improves visual quality. Compression is optimized to maintain clarity while reducing file size." },
    ],
  },

  // ── Phase 1 Additional (from Confluence, as coming soon) ──
  {
    slug: "auto-video-generator",
    name: "Auto Video Generator",
    tagline: "Create YouTube property videos from your photos",
    description: "Automatically generate professional property tour videos from your photos. Add music, transitions, text overlays, and branding — ready to upload to YouTube and social media.",
    category: "creation",
    status: "comingSoon",
    roles: ["pmc", "agent"],
    icon: "video",
    color: "red",
    hasDemo: false,
    features: ["Photo-to-video conversion", "Music library", "Text overlays", "Brand watermark", "YouTube-ready export"],
    useCases: [{ role: "PMCs", cases: ["Create virtual property tours", "Generate social media content"] }],
  },
  {
    slug: "whatsapp-share-tool",
    name: "WhatsApp Share Tool",
    tagline: "Share property links with one click via WhatsApp",
    description: "Generate and share beautifully formatted property links, quotes, and availability info directly through WhatsApp. Includes preview cards and tracking.",
    category: "distribution",
    status: "comingSoon",
    roles: ["pmc", "agent", "serviceProvider"],
    icon: "share",
    color: "green",
    hasDemo: false,
    features: ["One-click WhatsApp sharing", "Rich link previews", "Click tracking", "Bulk send lists"],
    useCases: [{ role: "Agents", cases: ["Share property options with clients", "Send booking confirmations"] }],
  },
  {
    slug: "client-proposal-builder",
    name: "Client Proposal Builder",
    tagline: "Build professional proposals that close deals",
    description: "Create stunning client proposals with property details, pricing, photos, and terms. Track when proposals are viewed and accepted.",
    category: "creation",
    status: "comingSoon",
    roles: ["agent", "pmc"],
    icon: "briefcase",
    color: "indigo",
    hasDemo: false,
    features: ["Drag-and-drop proposal builder", "Branded templates", "View tracking", "E-signature ready", "PDF export"],
    useCases: [{ role: "Agents", cases: ["Present vacation packages", "Propose real estate deals", "Bundle services for groups"] }],
  },
  {
    slug: "lead-form-generator",
    name: "Lead Form Generator + CRM Export",
    tagline: "Create custom lead forms with CRM integration",
    description: "Build custom lead capture forms with drag-and-drop. Embed on your website or share as links. Auto-export leads to your CRM or spreadsheet.",
    category: "system",
    status: "comingSoon",
    roles: ["pmc", "serviceProvider"],
    icon: "form",
    color: "orange",
    hasDemo: false,
    features: ["Drag-and-drop form builder", "Embeddable widgets", "CRM auto-export", "Lead scoring", "Notification rules"],
    useCases: [{ role: "PMCs", cases: ["Capture owner inquiries", "Build guest mailing lists"] }],
  },
  {
    slug: "review-management-dashboard",
    name: "Review Management Dashboard",
    tagline: "Monitor and respond to reviews across all platforms",
    description: "Aggregate reviews from Airbnb, Booking.com, Google, and TripAdvisor in one dashboard. Get alerts, generate AI-powered responses, and track sentiment trends.",
    category: "insights",
    status: "comingSoon",
    roles: ["owner", "pmc", "serviceProvider", "all"],
    icon: "star",
    color: "yellow",
    hasDemo: false,
    features: ["Multi-platform review aggregation", "AI response suggestions", "Sentiment analysis", "Alert system", "Trend reports"],
    useCases: [{ role: "Owners", cases: ["Monitor property reviews", "Respond quickly to negative feedback"] }],
  },
  {
    slug: "bulk-listing-importer",
    name: "Bulk Listing Importer",
    tagline: "Import property listings from CSV or API in bulk",
    description: "Bulk-import properties from spreadsheets, channel managers, or API feeds. Map fields, validate data, and publish listings across ClickyTour ecosystem.",
    category: "system",
    status: "comingSoon",
    roles: ["pmc"],
    icon: "upload",
    color: "slate",
    hasDemo: false,
    features: ["CSV/Excel import", "Field mapping wizard", "Validation checks", "Duplicate detection", "API feed support"],
    useCases: [{ role: "PMCs", cases: ["Migrate portfolio from another platform", "Sync from channel manager"] }],
  },
  {
    slug: "service-bundler",
    name: "Service Bundler Tool",
    tagline: "Package multiple services into sellable bundles",
    description: "Combine multiple services (cleaning + transfers + activities) into branded packages with bundled pricing. Perfect for upselling and cross-selling.",
    category: "creation",
    status: "comingSoon",
    roles: ["serviceProvider"],
    icon: "package",
    color: "teal",
    hasDemo: false,
    features: ["Drag-and-drop bundle builder", "Bundle pricing rules", "Branded package pages", "Shareable bundle links"],
    useCases: [{ role: "Service Providers", cases: ["Create welcome packages", "Bundle seasonal activities", "Cross-sell related services"] }],
  },
  {
    slug: "commission-calculator",
    name: "Commission Calculator",
    tagline: "Calculate your agent earnings per booking",
    description: "Instantly calculate commission earnings based on booking value, property type, and partnership tier. Compare scenarios and project annual income.",
    category: "calculator",
    status: "active",
    roles: ["agent"],
    primaryRole: "agent",
    icon: "calculator",
    color: "indigo",
    hasDemo: true,
    demoMode: "sandbox",
    features: ["Real-time commission calculation", "Multi-tier support", "Annual income projections", "Scenario comparison", "Export earnings report"],
    useCases: [{ role: "Agents", cases: ["Estimate earnings from new partnerships", "Compare commission structures", "Project seasonal income"] }],
    inputs: ["Booking value", "Commission tier", "Property type", "Number of bookings"],
    outputs: ["Commission amount", "Annual projection", "PDF report"],
  },
  {
    slug: "rental-income-estimator",
    name: "Rental Income Estimator",
    tagline: "Estimate your vacation rental income by region",
    description: "Compare your property against regional market data. Get estimated nightly rates, occupancy rates, and annual revenue projections based on location, property type, and amenities.",
    category: "calculator",
    status: "active",
    roles: ["owner"],
    primaryRole: "owner",
    icon: "chart",
    color: "emerald",
    hasDemo: true,
    demoMode: "sandbox",
    features: ["Regional market data comparison", "Seasonal rate projections", "Amenity impact analysis", "Revenue optimization tips", "Shareable estimate link"],
    useCases: [{ role: "Owners", cases: ["Evaluate rental potential before listing", "Optimize pricing strategy", "Compare properties across regions"] }],
    inputs: ["Location/region", "Property type", "Bedrooms", "Amenities", "Current rate (optional)"],
    outputs: ["Estimated nightly rate range", "Projected annual revenue", "Occupancy rate estimate", "Market comparison"],
  },
];

export const TOOL_CATEGORIES = [
  { slug: "creation", label: "Creation", icon: "pencil", description: "Content, media, and document generation" },
  { slug: "optimization", label: "Optimization", icon: "sliders", description: "Listings, pricing, and image enhancement" },
  { slug: "distribution", label: "Distribution", icon: "share", description: "Marketing, sharing, and outreach" },
  { slug: "insights", label: "Insights", icon: "chart", description: "Analytics, dashboards, and reporting" },
  { slug: "system", label: "System", icon: "cog", description: "Imports, integrations, and automation" },
  { slug: "calculator", label: "Calculators", icon: "calculator", description: "ROI, budgets, and estimators" },
] as const;

export const TOOL_ROLES = [
  { slug: "owner", label: "Property Owners" },
  { slug: "pmc", label: "Property Managers" },
  { slug: "agent", label: "Agents & Brokers" },
  { slug: "serviceProvider", label: "Service Providers" },
  { slug: "guest", label: "Guests" },
  { slug: "all", label: "All Users" },
] as const;

export function getToolBySlug(slug: string): Tool | undefined {
  return TOOLS.find((t) => t.slug === slug);
}

export function getToolsByRole(role: string): Tool[] {
  return TOOLS.filter((t) => t.roles.includes(role as any) || t.roles.includes("all"));
}

export function getToolsByCategory(category: string): Tool[] {
  return TOOLS.filter((t) => t.category === category);
}

export function getActiveTools(): Tool[] {
  return TOOLS.filter((t) => t.status === "active");
}
