/* ── Mock data for marketplace directories (design-first) ── */

import type { DirectoryItem, PoolCard } from "./types";

/** Mock pool cards (PMC ↔ Owners pool) */
export const MOCK_POOL_CARDS: PoolCard[] = [
  {
    ref: "CTV-A1B2C3",
    createdAtIso: "2026-02-18T10:30:00Z",
    role: "owner",
    subrole: "vacation",
    leadName: "Property in Crete",
    propertyType: "Villa",
    region: "Crete",
    city: "Chania",
    country: "Greece",
    bedrooms: "4",
    bathrooms: "3",
    maxGuests: "8",
    squareMeters: "220",
    hasPool: true,
    poolType: "Private",
    desiredNetoRate: "150",
    priceDescriptionPer: "per night",
    availableFromDate: "2026-04-01",
    tags: ["Vacation Rental", "Full Management"],
    images: [],
    pmcUrl: "#",
    fullUrl: "#",
  },
  {
    ref: "CTV-D4E5F6",
    createdAtIso: "2026-02-17T14:15:00Z",
    role: "owner",
    subrole: "vacation",
    leadName: "Apartment in Mykonos",
    propertyType: "Apartment",
    region: "Mykonos",
    city: "Mykonos Town",
    country: "Greece",
    bedrooms: "2",
    bathrooms: "1",
    maxGuests: "4",
    squareMeters: "85",
    hasPool: false,
    poolType: "",
    desiredNetoRate: "120",
    priceDescriptionPer: "per night",
    availableFromDate: "2026-05-01",
    tags: ["Vacation Rental", "Guest Ops"],
    images: [],
    pmcUrl: "#",
    fullUrl: "#",
  },
  {
    ref: "CTV-G7H8I9",
    createdAtIso: "2026-02-16T09:00:00Z",
    role: "owner",
    subrole: "real-estate",
    leadName: "House in Athens",
    propertyType: "House",
    region: "Athens",
    city: "Glyfada",
    country: "Greece",
    bedrooms: "3",
    bathrooms: "2",
    maxGuests: "6",
    squareMeters: "150",
    hasPool: true,
    poolType: "Shared",
    desiredNetoRate: "350000",
    priceDescriptionPer: "total",
    availableFromDate: "2026-03-01",
    tags: ["Real Estate", "RE Support"],
    images: [],
    pmcUrl: "#",
    fullUrl: "#",
  },
  {
    ref: "CTV-J1K2L3",
    createdAtIso: "2026-02-15T16:45:00Z",
    role: "owner",
    subrole: "vacation",
    leadName: "Seaside Villa Halkidiki",
    propertyType: "Villa",
    region: "Halkidiki",
    city: "Kassandra",
    country: "Greece",
    bedrooms: "5",
    bathrooms: "4",
    maxGuests: "10",
    squareMeters: "300",
    hasPool: true,
    poolType: "Infinity",
    desiredNetoRate: "250",
    priceDescriptionPer: "per night",
    availableFromDate: "2026-06-01",
    tags: ["Vacation Rental", "Luxury/Villas", "Full Management"],
    images: [],
    pmcUrl: "#",
    fullUrl: "#",
  },
];

/** Mock PMC directory items */
export const MOCK_PMC_ITEMS: DirectoryItem[] = [
  {
    id: "pmc-1",
    type: "pmc",
    name: "Aegean Property Management",
    subtitle: "Full-service vacation rental management",
    description: "Leading property management company in Crete specializing in luxury villas and vacation rentals. 10+ years experience, 150+ properties managed.",
    category: "Full Management",
    region: "Crete",
    city: "Heraklion",
    country: "Greece",
    coverPhoto: "/images/placeholder-pmc.jpg",
    rating: 4.8,
    reviewCount: 47,
    tags: ["Full Management", "Guest Ops", "Revenue Management", "Luxury/Villas"],
    badges: ["Top Rated", "150+ Properties"],
    verifiedBadge: true,
    gated: {
      phone: "+30 281 0XX XXXX",
      email: "info@aegeanpm.example",
      website: "https://aegeanpm.example",
    },
    meta: { managedProperties: 152, yearsExperience: 12, languages: "EN, GR, DE" },
    href: "/directory/property-managers/aegean-property-management",
    createdAt: "2025-06-15T00:00:00Z",
    status: "available",
  },
  {
    id: "pmc-2",
    type: "pmc",
    name: "Island Stays Management",
    subtitle: "Boutique management for island properties",
    description: "Specialized in Cycladic island properties. Personalized service for boutique villas and apartments in Mykonos, Santorini, and Paros.",
    category: "Guest Ops",
    region: "Mykonos",
    city: "Mykonos",
    country: "Greece",
    coverPhoto: "/images/placeholder-pmc.jpg",
    rating: 4.6,
    reviewCount: 29,
    tags: ["Guest Ops", "Check-in/Check-out", "Cleaning & Linen", "Channel Manager"],
    badges: ["Island Specialist"],
    verifiedBadge: true,
    gated: {
      phone: "+30 228 9XX XXXX",
      email: "hello@islandstays.example",
      website: "https://islandstays.example",
    },
    meta: { managedProperties: 45, yearsExperience: 7, languages: "EN, GR, FR" },
    href: "/directory/property-managers/island-stays-management",
    createdAt: "2025-09-20T00:00:00Z",
    status: "available",
  },
  {
    id: "pmc-3",
    type: "pmc",
    name: "Athens Urban Living",
    subtitle: "City apartment management experts",
    description: "Urban property management focused on Athens short-term and long-term rentals. Airbnb Superhost partner with full-stack city apartment services.",
    category: "City Apartments",
    region: "Athens",
    city: "Athens",
    country: "Greece",
    coverPhoto: "/images/placeholder-pmc.jpg",
    rating: 4.5,
    reviewCount: 63,
    tags: ["City Apartments", "Full Management", "Owner Reporting", "Revenue Management"],
    badges: ["Airbnb Superhost Partner", "200+ Properties"],
    verifiedBadge: false,
    gated: {
      phone: "+30 210 XXX XXXX",
      email: "contact@athensurban.example",
      website: "https://athensurban.example",
    },
    meta: { managedProperties: 210, yearsExperience: 5, languages: "EN, GR" },
    href: "/directory/property-managers/athens-urban-living",
    createdAt: "2025-11-01T00:00:00Z",
    status: "available",
  },
];

/** Mock service provider items */
export const MOCK_SERVICE_ITEMS: DirectoryItem[] = [
  {
    id: "sp-1",
    type: "service",
    name: "Sparkle Clean Crete",
    subtitle: "Professional villa & apartment cleaning",
    description: "Premium turnover cleaning for vacation rentals. Same-day service, eco-friendly products, linen included. Serving all of Crete.",
    category: "cleaning",
    region: "Crete",
    city: "Heraklion",
    country: "Greece",
    rating: 4.9,
    reviewCount: 84,
    tags: ["Cleaning", "Linen", "Turnover", "Eco-Friendly"],
    badges: ["Top Rated", "Same-Day Service"],
    verifiedBadge: true,
    gated: { phone: "+30 XXX", email: "info@sparklecrete.example", website: "https://sparklecrete.example" },
    meta: { pricingTier: "$$", responseTime: "< 1h" },
    href: "/directory/services/sparkle-clean-crete",
    createdAt: "2025-08-01T00:00:00Z",
    status: "available",
  },
  {
    id: "sp-2",
    type: "service",
    name: "Crete Transfers Pro",
    subtitle: "Airport & port transfers across Crete",
    description: "Reliable airport transfers, port pickups, and private tours. Fleet of 20+ vehicles from sedans to minibuses. 24/7 availability.",
    category: "transfers",
    region: "Crete",
    city: "Chania",
    country: "Greece",
    rating: 4.7,
    reviewCount: 156,
    tags: ["Transfers", "Airport", "Private Tours", "24/7"],
    badges: ["156 Reviews", "24/7 Available"],
    verifiedBadge: true,
    gated: { phone: "+30 XXX", email: "book@cretetransfers.example", website: "https://cretetransfers.example" },
    meta: { pricingTier: "$$", responseTime: "< 30min" },
    href: "/directory/services/crete-transfers-pro",
    createdAt: "2025-07-15T00:00:00Z",
    status: "available",
  },
];

/** Mock agent items */
export const MOCK_AGENT_ITEMS: DirectoryItem[] = [
  {
    id: "ag-1",
    type: "agent",
    name: "Hellenic Travel Partners",
    subtitle: "Licensed travel agency — Greece specialist",
    description: "Full-service travel agency specializing in Greek island packages. FIT and group tours, villa bookings, corporate retreats. GNTO licensed.",
    category: "travel-agents",
    region: "Athens",
    city: "Athens",
    country: "Greece",
    rating: 4.7,
    reviewCount: 92,
    tags: ["Travel Agent", "Island Packages", "Corporate", "GNTO Licensed"],
    badges: ["GNTO Licensed", "15+ Years"],
    verifiedBadge: true,
    gated: { phone: "+30 XXX", email: "info@hellenictravel.example", website: "https://hellenictravel.example" },
    meta: { yearsExperience: 15, markets: "EU, US, UK" },
    href: "/directory/agents/hellenic-travel-partners",
    createdAt: "2025-05-01T00:00:00Z",
    status: "available",
  },
];

/** Mock staff/job seeker items */
export const MOCK_STAFF_ITEMS: DirectoryItem[] = [
  {
    id: "js-1",
    type: "staff",
    name: "Maria K.",
    subtitle: "Experienced housekeeper & turnover specialist",
    description: "5 years in vacation rental cleaning. Fluent in Greek and English. Available for daily turnovers in Halkidiki region. References available.",
    category: "cleaner",
    region: "Halkidiki",
    city: "Kassandra",
    country: "Greece",
    rating: 4.9,
    reviewCount: 12,
    tags: ["Cleaner", "Turnover", "Halkidiki"],
    badges: ["Available Now"],
    verifiedBadge: false,
    gated: { phone: "+30 XXX", email: "maria@example.com" },
    meta: { availability: "Immediate", languages: "GR, EN", experience: "5 years" },
    href: "/directory/staff/maria-k",
    createdAt: "2026-01-10T00:00:00Z",
    status: "available",
  },
];

/** Mock hotel items */
export const MOCK_HOTEL_ITEMS: DirectoryItem[] = [
  {
    id: "htl-1",
    type: "hotel",
    name: "Olive Grove Boutique Hotel",
    subtitle: "4-star boutique hotel in Chania Old Town",
    description: "Charming 20-room boutique hotel in the heart of Chania's Venetian harbor. Rooftop restaurant, spa, and personalized concierge service.",
    category: "boutique",
    region: "Crete",
    city: "Chania",
    country: "Greece",
    rating: 4.8,
    reviewCount: 234,
    tags: ["Boutique", "Spa", "Restaurant", "Harbor View"],
    badges: ["Travellers' Choice 2025"],
    verifiedBadge: true,
    gated: { phone: "+30 XXX", email: "reservations@olivegrove.example", website: "https://olivegrove.example" },
    meta: { starRating: 4, rooms: 20, priceRange: "€€€" },
    href: "/directory/hotels/olive-grove-boutique",
    createdAt: "2025-04-01T00:00:00Z",
    status: "available",
  },
];

/** Get all mock items by directory type */
export function getMockDirectoryItems(type?: string): DirectoryItem[] {
  if (!type) return [...MOCK_PMC_ITEMS, ...MOCK_SERVICE_ITEMS, ...MOCK_AGENT_ITEMS, ...MOCK_STAFF_ITEMS, ...MOCK_HOTEL_ITEMS];
  switch (type) {
    case "pmc": return MOCK_PMC_ITEMS;
    case "service": return MOCK_SERVICE_ITEMS;
    case "agent": return MOCK_AGENT_ITEMS;
    case "staff": return MOCK_STAFF_ITEMS;
    case "hotel": return MOCK_HOTEL_ITEMS;
    default: return [];
  }
}
